// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CloudService 云端服务（Wails 暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../cloud/client/models.js";

/**
 * Connect 连接到云端（不返回 error，避免 Wails 打印 ERR 日志）
 * @param {string} serverAddr
 * @param {string} token
 * @returns {$CancellablePromise<boolean>}
 */
export function Connect(serverAddr, token) {
    return $Call.ByID(1382358538, serverAddr, token);
}

/**
 * Disconnect 断开连接
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1680499054);
}

/**
 * IsConnected 检查是否连接
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected() {
    return $Call.ByID(374592675);
}

/**
 * PullSync 拉取同步数据
 * @returns {$CancellablePromise<client$0.SyncConnection[]>}
 */
export function PullSync() {
    return $Call.ByID(517663660).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PushSync 推送同步数据
 * @param {client$0.SyncConnection[]} connections
 * @returns {$CancellablePromise<void>}
 */
export function PushSync(connections) {
    return $Call.ByID(3552283467, connections);
}

/**
 * SetApp 设置应用实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(582020831, app);
}

// Private type creation functions
const $$createType0 = client$0.SyncConnection.createFrom;
const $$createType1 = $Create.Array($$createType0);
