// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHService SSH服务结构体，供前端调用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddConnection 添加新连接（保存到本地）
 * @param {$models.ConnectionInfo | null} conn
 * @returns {$CancellablePromise<void>}
 */
export function AddConnection(conn) {
    return $Call.ByID(3337704262, conn);
}

/**
 * AddToGroup 将连接添加到分组
 * @param {string} groupID
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function AddToGroup(groupID, connID) {
    return $Call.ByID(3511777630, groupID, connID);
}

/**
 * AutoReconnect 自动重连（后台执行，不阻塞前端）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function AutoReconnect(connID) {
    return $Call.ByID(901282473, connID);
}

/**
 * CancelDirectoryUpload 取消目录上传
 * @returns {$CancellablePromise<void>}
 */
export function CancelDirectoryUpload() {
    return $Call.ByID(1383159405);
}

/**
 * CancelSearch 取消正在进行的搜索
 * @param {string} connID
 * @param {string} searchID
 * @returns {$CancellablePromise<void>}
 */
export function CancelSearch(connID, searchID) {
    return $Call.ByID(3549439085, connID, searchID);
}

/**
 * CheckConnectionHealth 检查连接健康状态（心跳检测）
 * @param {string} connID
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckConnectionHealth(connID) {
    return $Call.ByID(2865024575, connID);
}

/**
 * ClearWindowPositions 清除所有窗口位置记忆
 * @returns {$CancellablePromise<void>}
 */
export function ClearWindowPositions() {
    return $Call.ByID(2395729340);
}

/**
 * CloseGroup 关闭分组（断开所有连接并删除分组）
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function CloseGroup(groupID) {
    return $Call.ByID(368457684, groupID);
}

/**
 * CloseShellSession 关闭Shell会话（兼容旧调用，默认 session）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function CloseShellSession(connID) {
    return $Call.ByID(1241023307, connID);
}

/**
 * CloseShellSessionByID 关闭指定 session
 * @param {string} connID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseShellSessionByID(connID, sessionID) {
    return $Call.ByID(254181739, connID, sessionID);
}

/**
 * Connect 连接到SSH服务器
 * @param {string} connID
 * @param {$models.SSHConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function Connect(connID, config) {
    return $Call.ByID(3158583579, connID, config);
}

/**
 * CreateAndConnect 创建新连接并建立SSH连接（后端生成ID）
 * 流程：
 * 1. 生成唯一 connID
 * 2. 保存连接配置到本地存储
 * 3. 建立 SSH 连接
 * 4. 添加到默认分组
 * 5. 返回 connID 供前端打开窗口
 * @param {$models.SSHConfig | null} config
 * @returns {$CancellablePromise<string>}
 */
export function CreateAndConnect(config) {
    return $Call.ByID(2008681118, config);
}

/**
 * CreateAndConnectWithGroup 创建连接并指定分组
 * @param {$models.SSHConfig | null} config
 * @param {string} groupID
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function CreateAndConnectWithGroup(config, groupID) {
    return $Call.ByID(2799883501, config, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateArchive 创建压缩包并返回临时文件路径
 * @param {string} connID
 * @param {string[]} files
 * @param {string} archiveName
 * @returns {$CancellablePromise<string>}
 */
export function CreateArchive(connID, files, archiveName) {
    return $Call.ByID(3055432047, connID, files, archiveName);
}

/**
 * CreateDirectory 创建目录
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function CreateDirectory(connID, remotePath) {
    return $Call.ByID(4070708566, connID, remotePath);
}

/**
 * CreateGroup 创建新分组
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CreateGroup(name) {
    return $Call.ByID(2092665030, name);
}

/**
 * DeleteConnection 删除连接
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(773536852, id);
}

/**
 * DeleteFile 删除文件
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(connID, remotePath) {
    return $Call.ByID(4034412242, connID, remotePath);
}

/**
 * DeleteTempFile 删除临时文件
 * @param {string} connID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTempFile(connID, filePath) {
    return $Call.ByID(522402308, connID, filePath);
}

/**
 * Disconnect 断开SSH连接（删除缓存记录，保留永久记录）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(connID) {
    return $Call.ByID(3415423677, connID);
}

/**
 * DownloadFile 下载文件（返回字节数组）
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFile(connID, remotePath) {
    return $Call.ByID(531113469, connID, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * ExecuteCommand 执行远程命令
 * @param {string} connID
 * @param {string} command
 * @returns {$CancellablePromise<$models.CommandResult | null>}
 */
export function ExecuteCommand(connID, command) {
    return $Call.ByID(1426742331, connID, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ExtractArchive 解压压缩包到指定目录
 * @param {string} connID
 * @param {string} archivePath
 * @param {string} targetDir
 * @returns {$CancellablePromise<void>}
 */
export function ExtractArchive(connID, archivePath, targetDir) {
    return $Call.ByID(3411897738, connID, archivePath, targetDir);
}

/**
 * GetAllConnections 获取所有保存的连接（包含分组ID和真实在线状态）
 * @returns {$CancellablePromise<($models.ConnectionInfo | null)[]>}
 */
export function GetAllConnections() {
    return $Call.ByID(1034049049).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAllGroups 获取所有分组
 * @returns {$CancellablePromise<($models.SSHGroup | null)[]>}
 */
export function GetAllGroups() {
    return $Call.ByID(1349755672).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetApp 获取 Wails 应用实例（供其他服务使用）
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function GetApp() {
    return $Call.ByID(1769342176).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetClient 获取指定连接的 SSHClient（供其他服务使用）
 * @param {string} connID
 * @returns {$CancellablePromise<$models.SSHClient | null>}
 */
export function GetClient(connID) {
    return $Call.ByID(1531377098, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetConnection 获取单个连接
 * @param {string} id
 * @returns {$CancellablePromise<$models.ConnectionInfo | null>}
 */
export function GetConnection(id) {
    return $Call.ByID(4157586749, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetConnectionList 获取所有连接ID列表
 * @returns {$CancellablePromise<string[]>}
 */
export function GetConnectionList() {
    return $Call.ByID(3687271801).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetDefaultGroupID 获取默认分组ID
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultGroupID() {
    return $Call.ByID(3600154496);
}

/**
 * GetGroupByConnID 根据连接ID获取所属分组
 * @param {string} connID
 * @returns {$CancellablePromise<$models.SSHGroup | null>}
 */
export function GetGroupByConnID(connID) {
    return $Call.ByID(1817464098, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetGroupConnectionInfos 获取指定分组的完整连接信息
 * @param {string} groupID
 * @returns {$CancellablePromise<($models.ConnectionInfo | null)[]>}
 */
export function GetGroupConnectionInfos(groupID) {
    return $Call.ByID(3673563053, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetGroupConnections 获取指定分组的所有连接
 * @param {string} groupID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetGroupConnections(groupID) {
    return $Call.ByID(3120544729, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetLatency 获取连接延迟（实时测量）
 * @param {string} connID
 * @returns {$CancellablePromise<number>}
 */
export function GetLatency(connID) {
    return $Call.ByID(1884101629, connID);
}

/**
 * GetProcessDetail 获取进程详细信息
 * @param {string} connID
 * @param {number} pid
 * @returns {$CancellablePromise<string>}
 */
export function GetProcessDetail(connID, pid) {
    return $Call.ByID(3104965711, connID, pid);
}

/**
 * GetProcessList 获取进程列表
 * @param {string} connID
 * @returns {$CancellablePromise<$models.ProcessInfo[]>}
 */
export function GetProcessList(connID) {
    return $Call.ByID(2250757402, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetServerKey 根据连接 ID 返回服务器标识（host:port），供 AI 历史存储使用
 * @param {string} connID
 * @returns {$CancellablePromise<string>}
 */
export function GetServerKey(connID) {
    return $Call.ByID(3658321309, connID);
}

/**
 * GetSessionIDs 获取连接的所有活跃 session ID
 * @param {string} connID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSessionIDs(connID) {
    return $Call.ByID(1511821671, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetSystemStats 获取系统资源统计
 * @param {string} connID
 * @returns {$CancellablePromise<$models.SystemStats | null>}
 */
export function GetSystemStats(connID) {
    return $Call.ByID(1584700371, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * IsConnected 检查连接状态
 * @param {string} connID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected(connID) {
    return $Call.ByID(21186686, connID);
}

/**
 * IsDirectoryUploadCancelled 检查是否被取消
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDirectoryUploadCancelled() {
    return $Call.ByID(3776537678);
}

/**
 * IsShellActive 检查Shell会话是否活跃（兼容旧调用，默认 session）
 * @param {string} connID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsShellActive(connID) {
    return $Call.ByID(2700097313, connID);
}

/**
 * IsShellSessionActive 检查指定 session 是否活跃
 * @param {string} connID
 * @param {string} sessionID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsShellSessionActive(connID, sessionID) {
    return $Call.ByID(2118803755, connID, sessionID);
}

/**
 * KillProcess 终止进程
 * @param {string} connID
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function KillProcess(connID, pid) {
    return $Call.ByID(2446628692, connID, pid);
}

/**
 * ListDirectory 列出目录
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListDirectory(connID, remotePath) {
    return $Call.ByID(3991442742, connID, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ListFiles 列出目录内容
 * @param {string} connID
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListFiles(connID, path) {
    return $Call.ByID(816482758, connID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * OpenSSHWindow 打开SSH分组窗口（如果已存在则聚焦，否则创建新窗口）
 * @param {string} groupID
 * @param {string} groupName
 * @param {string} activeConnID
 * @returns {$CancellablePromise<void>}
 */
export function OpenSSHWindow(groupID, groupName, activeConnID) {
    return $Call.ByID(642898851, groupID, groupName, activeConnID);
}

/**
 * ReadFromShell 从Shell读取数据（兼容旧调用，默认 session）
 * @param {string} connID
 * @param {string} buf
 * @returns {$CancellablePromise<number>}
 */
export function ReadFromShell(connID, buf) {
    return $Call.ByID(4055578379, connID, buf);
}

/**
 * ReadFromShellSession 从指定 session 读取数据
 * @param {string} connID
 * @param {string} sessionID
 * @param {string} buf
 * @returns {$CancellablePromise<number>}
 */
export function ReadFromShellSession(connID, sessionID, buf) {
    return $Call.ByID(819790901, connID, sessionID, buf);
}

/**
 * Reconnect 重新连接（前端调用）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Reconnect(connID) {
    return $Call.ByID(4134368828, connID);
}

/**
 * RemoveFromGroup 从分组中移除连接
 * @param {string} groupID
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFromGroup(groupID, connID) {
    return $Call.ByID(1747012574, groupID, connID);
}

/**
 * RenameFile 重命名文件/目录
 * @param {string} connID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(connID, oldPath, newPath) {
    return $Call.ByID(4061368075, connID, oldPath, newPath);
}

/**
 * ResetDirectoryUploadCancel 重置取消标志
 * @returns {$CancellablePromise<void>}
 */
export function ResetDirectoryUploadCancel() {
    return $Call.ByID(3837316918);
}

/**
 * ResizeTerminal 调整终端大小（兼容旧调用）
 * @param {string} connID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(connID, cols, rows) {
    return $Call.ByID(2929959779, connID, cols, rows);
}

/**
 * ResizeTerminalByID 调整指定 session 的终端大小
 * @param {string} connID
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminalByID(connID, sessionID, cols, rows) {
    return $Call.ByID(2644263107, connID, sessionID, cols, rows);
}

/**
 * RunCommand 执行命令并返回输出字符串（供 AI 工具调用）
 * @param {string} connID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function RunCommand(connID, command) {
    return $Call.ByID(1438731577, connID, command);
}

/**
 * SaveConnection 标记连接为已保存
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SaveConnection(id) {
    return $Call.ByID(3519327366, id);
}

/**
 * SearchFiles 递归搜索文件（支持子目录，流式返回）
 * @param {string} connID
 * @param {string} basePath
 * @param {string} keyword
 * @param {string} searchID
 * @returns {$CancellablePromise<void>}
 */
export function SearchFiles(connID, basePath, keyword, searchID) {
    return $Call.ByID(2851111662, connID, basePath, keyword, searchID);
}

/**
 * SelectLocalDirectoryAndUpload 选择本地目录并上传到远程服务器
 * @param {string} connID
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function SelectLocalDirectoryAndUpload(connID, remotePath) {
    return $Call.ByID(441786227, connID, remotePath);
}

/**
 * SendSignal 向进程发送信号
 * @param {string} connID
 * @param {number} pid
 * @param {string} signal
 * @returns {$CancellablePromise<void>}
 */
export function SendSignal(connID, pid, signal) {
    return $Call.ByID(3358262813, connID, pid, signal);
}

/**
 * SetApp 设置Wails应用实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1606972132, app);
}

/**
 * SetWindowManager 设置窗口管理器
 * @param {$models.WindowManager | null} wm
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowManager(wm) {
    return $Call.ByID(1939515548, wm);
}

/**
 * StartHealthCheck 启动健康检查定时器
 * @returns {$CancellablePromise<void>}
 */
export function StartHealthCheck() {
    return $Call.ByID(2904328409);
}

/**
 * StartShellSession 启动Shell会话（兼容旧调用，默认 sessionID = "default"）
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function StartShellSession(connID) {
    return $Call.ByID(403655451, connID);
}

/**
 * StartShellSessionWithID 启动指定 ID 的 Shell 会话
 * @param {string} connID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StartShellSessionWithID(connID, sessionID) {
    return $Call.ByID(1129990798, connID, sessionID);
}

/**
 * SyncImportConnection 云端同步导入（按 host:port 去重：存在则更新，不存在则新增，永久保存）
 * @param {$models.ConnectionInfo | null} conn
 * @returns {$CancellablePromise<void>}
 */
export function SyncImportConnection(conn) {
    return $Call.ByID(1500372641, conn);
}

/**
 * TestConnection 测试SSH连接（连接成功后立即断开，不保存）
 * @param {$models.SSHConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(config) {
    return $Call.ByID(4100859731, config);
}

/**
 * UnsaveConnection 标记连接为未保存
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UnsaveConnection(id) {
    return $Call.ByID(31268393, id);
}

/**
 * UpdateConnection 更新连接信息
 * @param {$models.ConnectionInfo | null} conn
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConnection(conn) {
    return $Call.ByID(530342978, conn);
}

/**
 * UploadDirectory 上传目录
 * @param {string} connID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadDirectory(connID, localPath, remotePath) {
    return $Call.ByID(337594617, connID, localPath, remotePath);
}

/**
 * UploadFile 上传文件（从字节数组）
 * @param {string} connID
 * @param {string} remotePath
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(connID, remotePath, data) {
    return $Call.ByID(227251772, connID, remotePath, data);
}

/**
 * WriteToTerminal 向终端写入数据（兼容旧调用）
 * @param {string} connID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToTerminal(connID, data) {
    return $Call.ByID(156914611, connID, data);
}

/**
 * WriteToTerminalByID 向指定 session 写入数据
 * @param {string} connID
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToTerminalByID(connID, sessionID, data) {
    return $Call.ByID(3633996659, connID, sessionID, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.CommandResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.ConnectionInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.SSHGroup.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = application$0.App.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.SSHClient.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = $models.ProcessInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SystemStats.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.FileInfo.createFrom;
const $$createType19 = $Create.Array($$createType18);
